### ISSUE TITLE
Inference on Windows

### ISSUE THREAD

**Issue by devilismyfriend** [tloen/alpaca-lora#10]
Hi, would love to test the LORA model, did anyone try and do it on windows?

**Comment by devilismyfriend** [comment]
Update:

I managed to get it to work, here are some instructions:
1.created a new env with anaconda with python 3.8 (no particular reason for the version, just wanted to make sure everything will be compatible)
2.Installed Torch 13 with CUDA 11.6
3.Ran the lines provided here up to the bitsandbytes portion
4.Ran pip install bitsandbytes==0.35.0
5.Copied over the files here into the bitsandbytes folder https://github.com/devilismyfriend/StableTuner/tree/main/resources/bitsandbytes_windows

I didn't try training, but inference works.

**Comment by devilismyfriend** [comment]
Side not on performance, creative writing seems to be better on the Stanford one, I'm getting a lot of noinput results using the LORA.

**Comment by devilismyfriend** [comment]
On another note, I seem to be getting better performance when using the inference kwargs from the Stanford alpaca (https://github.com/tatsu-lab/stanford_alpaca/issues/35)

Here's the code snippet for anyone interested
`generation_config = GenerationConfig(
        temperature=0.7,
        top_p=0.9,
        num_beams=1,
        max_new_tokens=600,
        do_sample=True,
        **kwargs,
    )
    with torch.no_grad():
        generation_output = model.generate(
            input_ids=input_ids,
            generation_config=generation_config,
            return_dict_in_generate=True,
            output_scores=True,
        )`

**Comment by tloen** [comment]
@devilismyfriend are you noting this just for creative writing, or also for instruction-following? I've set the temperature really low to get "precise" outputs, which should come at the cost of creativity.

**Comment by devilismyfriend** [comment]
Well I'm giving it an instruction but it basically just repeated it to me most times (the instruction is to write a sentence based on another sentence)
