### ISSUE TITLE
simple playground share

### ISSUE THREAD

**Issue by deep-diver** [tloen/alpaca-lora#12]
not sure when I am going to shutdown, but I will leave this for few hours at least (running on RTX5000). maybe I will put things up in GKE later for tester purpose

NOTE: didn't do anything about maintaining the context yet

https://notebooksa.jarvislabs.ai/P1lDk5ziArYf6hVUkcne1vVlbwica44Ux7zNWyAeq-c69p-j0D1_ktPMmBKniGk8/

<img width="620" alt="스크린샷 2023-03-16 오전 9 41 13" src="https://user-images.githubusercontent.com/26025527/225480610-cc6f62a1-982f-48f1-bfe6-88b3cb448a3c.png">

**Comment by deep-diver** [comment]
any tips to speed up the inference speed?

**Comment by jasonborn0** [comment]
@deep-diver which model is this playground running? also what hardware?

**Comment by deep-diver** [comment]
it runs the model shared by @tloen on 7 core CPU / 32GB with a single RTX5000. I am hosting it in jarvislabs.ai
