### ISSUE TITLE
Thanks. I have played around to test its German capabilities. It's better than the 7b version that is great. Not sure if that is caused by the bigger dataset with that Llama 30b was grained with compared to the two smaller versions or if the bigger model is the reason.

### ISSUE THREAD

**Issue by savagesavag3141** [tloen/alpaca-lora#129]
Thanks. I have played around to test its German capabilities. It's better than the 7b version that is great. Not sure if that is caused by the bigger dataset with that Llama 30b was grained with compared to the two smaller versions or if the bigger model is the reason.

In my testing of multiple messages it only made one grammar error. Not perfect but it way better than 7b which didn't sound like a true native speaker of German.

Is that an 8 bit or 4bit version of the model?

And how does your code compare to the "text generation web ui" repo?

_Originally posted by @DanielWe2 in https://github.com/tloen/alpaca-lora/issues/87#issuecomment-1475822938_

**Comment by DanielWe2** [comment]
Why are you copying my comment on another issue here in this weird way even keeping my typos?

**Comment by tloen** [comment]
I'm not sure what the actionable here is. Closing.
