### ISSUE TITLE
Can't generate more then 256 new tokens.

### ISSUE THREAD

**Issue by baleksey** [tloen/alpaca-lora#13]
First of all - thank you for the code and model. Even for 7B it works awesome!

But I stumbled upon strange problem. It doesn't matter how I set generator param **max_new_tokens** or **max_length** (any big numbers like 2048) it always limit generation on 256 new tokens and stops without ending the sentence. While limiting to lower then 256 works as expected.

Is it hard-coded somewhere which I can edit for my setup?

**Comment by baleksey** [comment]
Good to know, thank you! This limitation made impossible also article stigmatization as even short input text article fills those 256 tokens instantly.

**Comment by tloen** [comment]
We're in business (updated the online weights):

![Screenshot_20230316_095131](https://user-images.githubusercontent.com/4811103/225693756-d0c88db9-0b17-4382-8639-807eeec5fefc.png)

Let me know if summarization gives poor results. I'm still training on the first 256 tokens and banking on the existing model to figure out how to extrapolate, so it's possible that we'll need to do a run with longer max_seq_len at some point.

**Comment by baleksey** [comment]
@tloen Well done! I can confirm, that now it can produce pretty large and almost meaningful texts above 256 tokens (tested with at last ~768 tokens long dialog)

But it's not very good at summarization. Sometimes it almost do the job but more often it just cant understand "make **short** sentence summary" and almost rewriting the input text. Maybe it's because of lack of training but I guess it's also could be about poor dataset (many examples are not good like one-two sentence input and almost the same size output). 

Can I also ask how can I load the initial 7B model released by Meta to use with your lora? If it's possible it would be great to reuse the model and just add different fine-tuned loras to it and avoid downloading new 12Gb model each time from HuggingFace :). If the base model must be prepared before using in your code - can you share script how you processed 7B to load and use in your generate.py from local folder? Thank you!

**Comment by tloen** [comment]
@baleksey For instructions on converting the weights to HF format, please see [the official HuggingFace documentation](https://huggingface.co/docs/transformers/main/en/model_doc/llama).

Thanks for the info on summarization performance. It shouldn't be too hard for someone to augment the Stanford Alpaca dataset with an existing summarization dataset and train with a larger max_seq_len :)
