### ISSUE TITLE
What to do after fine tuning?

### ISSUE THREAD

**Issue by lucluclucluclucluc** [tloen/alpaca-lora#133]
Hello
Sorry if the question is obvious, but once we finish running the finetune.py script with our own data, and it has created the "lora-alpaca" folder how to use the fine tuned model we just created with the generate.py script ?
Thanks for your help

**Comment by lucluclucluclucluc** [comment]
thx !

**Comment by sri9s** [comment]
How do you actually evaluate if the model has improved?
