### ISSUE TITLE
RuntimeError: mat1 and mat2 shapes cannot be multiplied (1024x6 and 7x4096)

### ISSUE THREAD

**Issue by Nikitala0014** [tloen/alpaca-lora#144]
I have two NVIDIA A10 24GB. When I start the finetune.py script I recieve this error on batch size 24. Can you help me understand what is the real problem? Thank's.

**Comment by chiayisu** [comment]
I encountered this errror as well. However, in my case, after I added "os.environ["CUDA_VISIBLE_DEVICES"] = "1" to restrict to use only one gpu, the problem was resolved.

**Comment by Nikitala0014** [comment]
> 

Thank you for your response. Indeed, this solved not only this problem, but for some reason only with this approach to launching on one gpu, 24GB of memory is enough for training.

**Comment by AngainorDev** [comment]
See this other - same - issue and answers

https://github.com/tloen/alpaca-lora/issues/8#issuecomment-1477490259

Training on multiple GPUs is possible with torchrun, you'll double batch size and half the training time.
Take care of veryfiying the math by hand so gradient accumulation steps is right.

**Comment by Nikitala0014** [comment]
> See this other - same - issue and answers
> 
> [#8 (comment)](https://github.com/tloen/alpaca-lora/issues/8#issuecomment-1477490259)
> 
> Training on multiple GPUs is possible with torchrun, you'll double batch size and half the training time. Take care of veryfiying the math by hand so gradient accumulation steps is right.

Thank you. That's what I need ;)
