### ISSUE TITLE
Fetch the newest version of alpaca-cleaned dataset 

### ISSUE THREAD

**Issue by eryk-mazus** [tloen/alpaca-lora#167]
Hi,

Would it make sense to fetch the newest version of alpaca-cleaned dataset instead of embedding the json directly in repo ?

If I'm correct it would require simple change from
```
data = load_dataset("json", data_files=data_path)
```
to:
```
data = load_dataset("yahma/alpaca-cleaned")
```

**Comment by claysauruswrecks** [comment]
Yeah, I like this idea better. I will refactor the PR https://github.com/tloen/alpaca-lora/pull/152

**Comment by claysauruswrecks** [comment]
@eryk-mazus - Fixed in https://github.com/tloen/alpaca-lora/pull/175

**Comment by eryk-mazus** [comment]
Thanks
