### ISSUE TITLE
Original LLaMA Models?

### ISSUE THREAD

**Issue by GreenTeaBD** [tloen/alpaca-lora#176]
Just a quick question, can this be used to finetune the original LLaMA models, not just alpaca? My goal isn't to finetune a chatbot, but a text generation AI.

**Comment by AngainorDev** [comment]
This repo allows to fine tune llama via LoRA.

The default dataset from this repo is Alpaca, but you can train a new LoRA from base llama with your own dataset, or use the Alpaca lora and fine tune from that base (llama + alpaca) with an extra dataset of yours.

**Comment by GreenTeaBD** [comment]
Great, thanks!
