### ISSUE TITLE
ValueError: When localhost is not accessible, a shareable link must be created. Please set share=True.

### ISSUE THREAD

**Issue by dsh54054** [tloen/alpaca-lora#192]
a inference error, Did anyone encounter the same error？ 

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
/tal-vePFS/SFT/dengshuhao1/local/anaconda3/envs/alpaca-lora/lib/python3.8/site-packages/bitsandbytes/cuda_setup/main.py:136: UserWarning: /tal-vePFS/SFT/dengshuhao1/local/anaconda3/envs/alpaca-lora did not contain libcudart.so as expected! Searching further paths...
  warn(msg)
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 8.0
CUDA SETUP: Detected CUDA version 115
CUDA SETUP: Loading binary /tal-vePFS/SFT/dengshuhao1/local/anaconda3/envs/alpaca-lora/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda115.so...
The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'LLaMATokenizer'. 
The class this function is called from is 'LlamaTokenizer'.
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 33/33 [00:14<00:00,  2.27it/s]
/tal-vePFS/SFT/dengshuhao1/local/anaconda3/envs/alpaca-lora/lib/python3.8/site-packages/gradio/inputs.py:27: UserWarning: Usage of gradio.inputs is deprecated, and will not be supported in the future, please import your component from gradio.components
  warnings.warn(
/tal-vePFS/SFT/dengshuhao1/local/anaconda3/envs/alpaca-lora/lib/python3.8/site-packages/gradio/deprecation.py:40: UserWarning: `optional` parameter is deprecated, and it has no effect
  warnings.warn(value)
/tal-vePFS/SFT/dengshuhao1/local/anaconda3/envs/alpaca-lora/lib/python3.8/site-packages/gradio/deprecation.py:40: UserWarning: `numeric` parameter is deprecated, and it has no effect
  warnings.warn(value)
Traceback (most recent call last):
  File "generate.py", line 192, in <module>
    fire.Fire(main)
  File "/tal-vePFS/SFT/dengshuhao1/local/anaconda3/envs/alpaca-lora/lib/python3.8/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/tal-vePFS/SFT/dengshuhao1/local/anaconda3/envs/alpaca-lora/lib/python3.8/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/tal-vePFS/SFT/dengshuhao1/local/anaconda3/envs/alpaca-lora/lib/python3.8/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "generate.py", line 114, in main
    gr.Interface(
  File "/tal-vePFS/SFT/dengshuhao1/local/anaconda3/envs/alpaca-lora/lib/python3.8/site-packages/gradio/blocks.py", line 1514, in launch
    raise ValueError(
ValueError: When localhost is not accessible, a shareable link must be created. Please set share=True._

**Comment by AngainorDev** [comment]
localhost not accessible? unusual setup.

This should be fixed by this PR, then calling with --gradio_share=true
https://github.com/tloen/alpaca-lora/pull/189

**Comment by dsh54054** [comment]
> localhost not accessible? unusual setup.
> 
> This should be fixed by this PR, then calling with --gradio_share=true #189

 I don't understand what you mean. Can you describe it more specifically?
