### ISSUE TITLE
Will this support 4bit quantisation?

### ISSUE THREAD

**Issue by distbit0** [tloen/alpaca-lora#2]
Awesome project. Thanks so much for creating a foss alpaca codebase.

**Comment by gururise** [comment]
> Most probably yes, you can merge the LoRA weights into the model and quantize that

Training in 4-bit or just 4-bit inference?

Training in 4-bit would be a game-changer.

**Comment by hyychong** [comment]
I think technically we can do this, origin model weight in int4+fp16/fp32 and lora weight of fp32. The dtype of output from QuantLinear layer can be exactly the dtype of its input, so inserting LoRA layer after every QuantLinear layer won't be very difficult.

**Comment by FNsi** [comment]
> Most probably yes, you can merge the LoRA weights into the model and quantize that
May I ask how to merge the Lora?
