### ISSUE TITLE
How much VRAM is required for each model?

### ISSUE THREAD

**Issue by teknium1** [tloen/alpaca-lora#221]
Can I train the lora in 8bit so that my 3090 can train a lora for 13B?

**Comment by AngainorDev** [comment]
Yes. 13B still fits on a 3090.

**Comment by teknium1** [comment]
> Yes. 13B still fits on a 3090.

So I can load the 13B into 8bit with hf transformers + peft and train a lora of 512+ ctx sizes in it?

**Comment by teknium1** [comment]
Thank you. Will begin working on getting this setup tonight. Appreciate it!
