### ISSUE TITLE
The difference between the two training methods？

### ISSUE THREAD

**Issue by WangRongsheng** [tloen/alpaca-lora#233]
method 1:
```python
python finetune.py \
    --base_model 'decapoda-research/llama-7b-hf' \
    --data_path 'yahma/alpaca-cleaned' \
    --output_dir './lora-alpaca' \
    --batch_size 128 \
    --micro_batch_size 4 \
    --num_epochs 3 \
    --learning_rate 1e-4 \
    --cutoff_len 512 \
    --val_set_size 2000 \
    --lora_r 8 \
    --lora_alpha 16 \
    --lora_dropout 0.05 \
    --lora_target_modules '[q_proj,v_proj]' \
    --train_on_inputs \
    --group_by_length
```

method 2:
```python
python finetune.py \
    --base_model='decapoda-research/llama-7b-hf' \
    --num_epochs=10 \
    --cutoff_len=512 \
    --group_by_length \
    --output_dir='./lora-alpaca' \
    --lora_target_modules='[q_proj,k_proj,v_proj,o_proj]' \
    --lora_r=16 \
    --micro_batch_size=8
```

How are they different?

**Comment by AngainorDev** [comment]
Many different parameters between the two examples here.

Most important change seems to be the additional modules in the second one, with higher rank LoRA.
This second config seems to be tailored for a larger and multilingual dataset (looks like guanaco), while the first one is good enough for a single language.

Higher LoRA rank and more LoRA modules means more data needed  in the training set and a longer training time.

**Comment by WangRongsheng** [comment]
thank you!

**Comment by tloen** [comment]
The first command is closer to the repo's default settings, which I used to rush out the very first alpaca-lora-7b on the day the paper was released. The second command is the one I used to retrain the "current" alpaca-lora-7b this week; it takes a bit more time and resources, but the output quality seems higher.

**Comment by ndvbd** [comment]
What is the "o_proj" layer? I know the q,k,v in attention, but what is "o"?

**Comment by LiuPearl1** [comment]
@AngainorDev lora_target_modules changing from [q_proj,v_proj] to [q_proj,k_proj,v_proj,o_proj] means more parameters be trained. I wonder lora_target_modules has other parameters apart from [q_proj,k_proj,v_proj,o_proj]?

**Comment by ndvbd** [comment]
> What is the "o_proj" layer? I know the q,k,v in attention, but what is "o"?

I believe it is described here: https://arxiv.org/pdf/1911.02150.pdf

**Comment by IvanKargapoltsev** [comment]
> What is the "o_proj" layer? I know the q,k,v in attention, but what is "o"?

It's part of the _MultiHead_ Attention formula in the original Attention Is All You Need paper (see 3.2.2, W<sup>O</sup>)
