### ISSUE TITLE
How to use generate.py with merged HF checkpoint?

### ISSUE THREAD

**Issue by danucalovj** [tloen/alpaca-lora#241]
I trained a 13B model on a custom cleaned json dataset. Tested successfully by using generate.py and pointing to the original base model and trained lora.

Now, used the HF checkpoint merger utility to merge the weights, which creates the hf_ckpt folder with the model bin files.

How do I now use it with generate.py?

First, it says tokenizer files are missing, so I copied those from the original llama-13b-hf folder.

I tried pointing generate.py to the hf_ckpt folder, which loads the weights fine but what should be the lora model? If I point lora to my trained lora model folder, when I create a prompt it spews up repetitive garbage. The same applies if I use the tloen/alpaca-lora-13b lora files.

Is there a way to point generate.py to just the hf_ckpt without any lora weights? Or maybe it's related to the tokenizer model?

**Comment by AngainorDev** [comment]
If you want to use a model without lora, comment out the peft part there
https://github.com/tloen/alpaca-lora/blob/9de612e582ab86013b5d1c3be6b0ed9f5ab2065a/generate.py#L47

But, what is the point of merging back into the model?
One of the advantages of the loras is to have several loras for a single base model, without having to merge back and handle big files.

The only reason I could see to merge would be to use other generators, that do not support Lora (yet).

**Comment by danucalovj** [comment]
Thanks @AngainorDev, I'll try that today. In terms of the tokenizer, is the approach of moving the original tokenizer files from the base model to the hf_ckpt folder correct?

My thought process was to run a first finetune job with new data from base, merge, the run a nightly job with new data to build on top of the finetuned model. But it seems from what I'm hearing my approach could be completely wrong.

**Comment by AngainorDev** [comment]
You can just not dup the tokenizer and leave it pointed to the base model (one more reason not to merge).

Even if you want to incrementally fine tune with several different datasets in sequence, just do it restarting from a previous lora.
Use the `--resume_from_checkpoint` with a previous lora you want to further tune.
You'll get a new lora, that still applies to the base llama model, and embeds the data from your various runs.
Easier also to keep different variants that way, and no need to merge back.

Note that I do this myself, start from an alpaca lora to further tune on a smaller dataset for instance.
I have no real idea if this better or worse than training on a larger (alpaca + mine) dataset from scratch.
This gives better results for me than training from scratch alone, but I'm pretty sure at some point it's worse than training from start with all the data at once. I believe each incremental train distorts the base model capabilities a bit more, in a less coherent way than training on all at a time.
All is a question of balance, right params, and remain consistent.
If your prompt structure changes too much or you want to learn a completely different set of features, better restart from alpaca, good generic basis, for instance.

**Comment by danucalovj** [comment]
Super helpful, thank you very much
