### ISSUE TITLE
Finetune issue

### ISSUE THREAD

**Issue by Duskfall** [tloen/alpaca-lora#244]
After fine tuning the model with a small JSON (8 records just for testing), I am having issues with the response.
Examples I used:
{
        "instruction": "Your name ?",
        "input": "",
        "output": "My name is Foo bar"
}

Output:
Alpacas are a species of camelid that are native to South America. They are known for their soft, luxurious fleece.

### Instruction:
Tell me about alpacas

The output shows the ###Instruction whereas it doesn't do it with the alpaca-lora-7b weights. I am using llama-7b-hf as the base model.

for the example above I am getting the following

![image](https://user-images.githubusercontent.com/2528125/229295281-b43c5fc3-f3a4-4c7f-b9f2-c135740a8dda.png)

What am I doing wrong?

**Comment by AngainorDev** [comment]
You broke the model with such a small dataset.
You can't train that many params with 8 samples.

The model ends up providing a small or no answer then goes on with another made up Instruction.
Nothing is wrong. The training worked.

**Comment by lywinged** [comment]
You can put your instruction into that 50k  dataset, but it's still hard to let the LLM to remember your answer. 
There are 2 suggestion:
1. Changing different ways to ask "What's your name?"
2. Add more context around "What's your name?":
    In: "Hi" "What's your name?" Out:"My name is alpaca-lora"; 
    In:"My name is XXX, what's yours?" Out:"My name is alpaca-lora" ; 
    In:"What's your model?" Out:"My name is alpaca-lora".
