### ISSUE TITLE
Attempting to finetune from an Alpaca-Lora checkpoint

### ISSUE THREAD

**Issue by aced125** [tloen/alpaca-lora#253]
```shell
WORLD_SIZE=1 CUDA_VISIBLE_DEVICES=0 torchrun --nproc_per_node=1 --master_port=1234 finetune.py \
    --base_model='decapoda-research/llama-7b-hf' \
    --num_epochs=10 \
    --cutoff_len=512 \
    --group_by_length \
    --output_dir='./my-output-dir' \
    --lora_target_modules='[q_proj,k_proj,v_proj,o_proj]' \
    --lora_r=16 \
    --batch_size=128 \
    --micro_batch_size=8 \
    --resume_from_checkpoint './lora-alpaca-output-dir/checkpoint-1800'
```

where `'./lora-alpaca-output-dir/checkpoint-1800'` is the original directory I saved the alpaca model to (training that from Llama worked fine).

The error I get for the above is:

```
RuntimeError: Expected to mark a variable ready only once. This error is caused by one of the following reasons: 1) Use of a module parameter outside the `forward` function. Please make sure model parameters are
not shared across multiple concurrent forward-backward passes. or try to use _set_static_graph() as a workaround if this module graph does not change during training loop.2) Reused parameters in multiple reentrant
backward passes. For example, if you use multiple `checkpoint` functions to wrap the same part of your model, it would result in the same set of parameters been used by different reentrant backward passes multiple
times, and hence marking a variable ready multiple times. DDP does not support such use cases in default. You can try to use _set_static_graph() as a workaround if your module graph does not change over iterations.
Parameter at index 255 has been marked as ready twice. This means that multiple autograd engine  hooks have fired for this particular parameter during this iteration. You can set the environment variable
TORCH_DISTRIBUTED_DEBUG to either INFO or DETAIL to print parameter names for further debugging.
```

**Comment by lywinged** [comment]
What is your hyperparameters for the "/lora-alpaca-output-dir/checkpoint-1800"? Did you output all of these four weight matrices?

**Comment by aced125** [comment]
They are the same, default lora hyperparams used in the repository.
```
    --lora_r 8 \
    --lora_alpha 16 \
    --lora_dropout 0.05 \
```

```python
    config = LoraConfig(
        r=lora_r,
        lora_alpha=lora_alpha,
        target_modules=lora_target_modules,
        lora_dropout=lora_dropout,
        bias="none",
        task_type="CAUSAL_LM",
    )
```

**Comment by lywinged** [comment]
The default lora hyperparams only output q_proj and v_proj, so you can't use the checkpoint directly. But you can generate the adapter model based on checkpoint-1800, and modify your finetune.py to resume the adapter model as following example.

#model = get_peft_model(model, config)
from peft import PeftModel
model=PeftModel.from_pretrained(model, "/lora-alpaca-output-dir")

**Comment by aced125** [comment]
@lywinged will try that now and lyk how it goes

**Comment by aced125** [comment]
@lywinged can confirm the above works, and is the same speed as without resuming from checkpoing. I also needed to add "device_map" to get it to work on multi-GPU.

```python
    if resume_from_checkpoint:
        model = PeftModel.from_pretrained(
            model,
            resume_from_checkpoint,
            torch_dtype=torch.float16,
            device_map=device_map,
        )
        resume_from_checkpoint = False  # Avoid trainer attempting to load state
    else:
        model = get_peft_model(model, config)
```

Thanks so much!

**Comment by lywinged** [comment]
> @lywinged can confirm the above works, and is the same speed as without resuming from checkpoing. I also needed to add "device_map" to get it to work on multi-GPU.
> 
> ```python
>     if resume_from_checkpoint:
>         model = PeftModel.from_pretrained(
>             model,
>             resume_from_checkpoint,
>             torch_dtype=torch.float16,
>             device_map=device_map,
>         )
>         resume_from_checkpoint = False  # Avoid trainer attempting to load state
>     else:
>         model = get_peft_model(model, config)
> ```
> 
> Thanks so much!

If you trained your 1800 with single GPU, just change the micro_batch_size=4, it doesn't affect your result.
