### ISSUE TITLE
How to migrate with export_hf_checkpoint.py

### ISSUE THREAD

**Issue by 15ky3** [tloen/alpaca-lora#254]
Hi, stupid question:

How can I migrate the adapter_model.bin with the alpaca 7B weights to one single file (to use with llama.cpp)

**Comment by Aasttha23** [comment]
In the export_hf_checkpoint.py file, you will find this piece of code:
lora_model = PeftModel.from_pretrained(
    base_model,
    "tloen/alpaca-lora-7b",
    device_map={"": "cpu"},
    torch_dtype=torch.float16,

Replace "tloen/alpaca-lora-7b" with the address of the directory where you have stored the adapter model. And then run :
export BASE_MODEL=decapoda-research/llama-7b-hf python export_hf_checkpoint.py

**Comment by 15ky3** [comment]
Thanks, it worked 👍

**Comment by cokuehuang** [comment]
@Aasttha23 Hi! The results of export_hf_checkpoint.py missing these files: special_tokens_map.json, tokenizer_config.json, tokenizer.model, and inference error: "OSError: Can't load tokenizer for '/alpaca-lora/lora_megre'. Should I copy those files from llama base model to the merged checkpoint?

**Comment by kocoten1992** [comment]
@cokuehuang Hi, have you find out how to fix that? I try copy from llama base model, but it not working.
