### ISSUE TITLE
train_on_inputs clarification

### ISSUE THREAD

**Issue by ElleLeonne** [tloen/alpaca-lora#255]
When you say train_on_inputs = False, I presume you mean to mask out the prompt, and train the loss only on the response that the model is supposed to produce.

This is made slightly confusing by the fact that the prompt itself has an "input" field. Signposting would seem to imply that you're only masking out the portion of the json with key "input". This should be changed for brevity.

I propose "train_on_inputs" should be renamed to "train_on_prompt"

**Comment by jquave** [comment]
Seems like it's masking out the instruction+input part of the tokenized prompt. So the label is correct, but confusing...

```
def generate_and_tokenize_prompt(data_point):
    full_prompt = prompter.generate_prompt(
        data_point["instruction"],
        data_point["input"],
        data_point["output"],
    )
    tokenized_full_prompt = tokenize(full_prompt)
    if not train_on_inputs:
        user_prompt = prompter.generate_prompt(
            data_point["instruction"], data_point["input"]
        )
        tokenized_user_prompt = tokenize(user_prompt, add_eos_token=False)
        user_prompt_len = len(tokenized_user_prompt["input_ids"])

        tokenized_full_prompt["labels"] = [
            -100
        ] * user_prompt_len + tokenized_full_prompt["labels"][
            user_prompt_len:
        ]  # could be sped up, probably
    return tokenized_full_prompt
    ```

**Comment by steveepreston** [comment]
This is still confusing. A simple example would be pleasing.
