### ISSUE TITLE
Error: ZeroDivisionError: integer division or modulo by zero

### ISSUE THREAD

**Issue by qingfengtommy** [tloen/alpaca-lora#260]
I have encountered the following errors when I trying run the command:

`python generate.py --load_8bit  --base_model 'decapoda-research/llama-7b-hf' --lora_weights 'tloen/alpaca-lora-7b'`

Traceback (most recent call last):
  File "C:\Users\Tommy\Desktop\WebDev\alpaca-lora\generate.py", line 196, in <module>
    fire.Fire(main)
  File "D:\Users\Tommy\anaconda3\lib\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "D:\Users\Tommy\anaconda3\lib\site-packages\fire\core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "D:\Users\Tommy\anaconda3\lib\site-packages\fire\core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "C:\Users\Tommy\Desktop\WebDev\alpaca-lora\generate.py", line 46, in main
    model = PeftModel.from_pretrained(
  File "D:\Users\Tommy\anaconda3\lib\site-packages\peft\peft_model.py", line 167, in from_pretrained
    max_memory = get_balanced_memory(
  File "D:\Users\Tommy\anaconda3\lib\site-packages\accelerate\utils\modeling.py", line 461, in get_balanced_memory
    per_gpu =  module_sizes[""] // (num_devices - 1 if low_zero else num_devices)
ZeroDivisionError: integer division or modulo by zero

However, I can run the inference successfully when I run it on the CPU.

My current environment:
Windows 11
RTX 3070
Cuda 11.8

**Comment by zoemaestra** [comment]
Replace the following in generate.py:

`model = LlamaForCausalLM.from_pretrained(
            base_model,
            load_in_8bit=load_8bit,
            torch_dtype=torch.float16,
        )
        model = PeftModel.from_pretrained(
            model,
            lora_weights,
            torch_dtype=torch.float16,
        )`
With this:
`model = LlamaForCausalLM.from_pretrained(
            base_model,
            load_in_8bit=load_8bit,
            torch_dtype=torch.float16,
            device_map={'': 0}
        )
        model = PeftModel.from_pretrained(
            model,
            lora_weights,
            torch_dtype=torch.float16,
            device_map={'': 0}
        )`

You may also need to go into the accelerate/utils folder in site-packages (or wherever else you keep your packages) and edit modeling.py.

Edit this line:
` max_memory = {i: torch.cuda.mem_get_info(i)[0] for i in range(torch.cuda.device_count())}`

to this:
` max_memory = {i: torch.cuda.mem_get_info(i)[1] for i in range(torch.cuda.device_count())}`

**Comment by qingfengtommy** [comment]
> Replace the following in generate.py:
> 
> ```
>             base_model,
>             load_in_8bit=load_8bit,
>             torch_dtype=torch.float16,
>         )
>         model = PeftModel.from_pretrained(
>             model,
>             lora_weights,
>             torch_dtype=torch.float16,
>         )
> ```
> 
> With this:
> 
> ```
>             base_model,
>             load_in_8bit=load_8bit,
>             torch_dtype=torch.float16,
>             device_map={'': 0}
>         )
>         model = PeftModel.from_pretrained(
>             model,
>             lora_weights,
>             torch_dtype=torch.float16,
>             device_map={'': 0}
>         )
> ```
> 
> You may also need to go into the accelerate/utils folder in site-packages (or wherever else you keep your packages) and edit modeling.py.
> 
> Edit this line: ` max_memory = {i: torch.cuda.mem_get_info(i)[0] for i in range(torch.cuda.device_count())}`
> 
> to this: ` max_memory = {i: torch.cuda.mem_get_info(i)[1] for i in range(torch.cuda.device_count())}`

This works! Thank you for your help!
