### ISSUE TITLE
New Alpaca 13b LoRA, newest more precise training.

### ISSUE THREAD

**Issue by AngainorDev** [tloen/alpaca-lora#270]
Hi @tloen ,

I know there are several 13b lora linked already.  
They seem of varying quality however (some Rank 4, some old training style, only 2 modules).  
Here is my newly trained one with its training settings:  
https://huggingface.co/Angainor/alpaca-lora-13b

Rank 16, 10 epochs, 4 modules.

**Comment by gururise** [comment]
On generation with oogabooga, I get the following error:
```
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
```

Not sure why. I've used several other 13b lora w/o problems in 8-bit.

**Comment by AngainorDev** [comment]
Thanks for the notice.
I did not try with oogabooga.

The GPUs are busy right now, but I'll redo some tests from the HF repo once the job is over and report.

**Comment by danucalovj** [comment]
Thanks for sharing @AngainorDev. Was looking at the HF model repo and saw the graphs, curious what exactly was the loss? Seems pretty damn good. My best loss training has been 0.78, can't seem to break that lower with the cleaned dataset, but will try now with your hyperparams

**Comment by AngainorDev** [comment]
> curious what exactly was the loss?

Default one. 

Things with an incidence could be:
- No validation (For this precise case, Alpaca dataset, aiming at diversity I find it better not to let samples apart and ignore validation, since the goal is to learn different enough stuff for it generalize). I also save at every epoch - not by steps - So I'm able to pick an earlier checkpoint if needed.
- Hard coded warmup steps (could be auto-computed) to 404 so it fitted exactly the first epoch (with my own batch params)
- No "Group by len" (faster but non random samples)
- Ofc , with more LoRA params: 10 epochs, 3 are not enough.

**Comment by gururise** [comment]
> Thanks for the notice. I did not try with oogabooga.
> 
> The GPUs are busy right now, but I'll redo some tests from the HF repo once the job is over and report.
> 
> Edit: Just checked, works from this repo generate (and HF hosted lora) I also installed the current oogabooga and it works as well.

Thanks. Don't know what was wrong, but it works now. Must have just needed a reboot of my PC. Sorry for the confusion.

**Comment by tloen** [comment]
Added this to the README. I was a little hesitant to include _r_ and the modules at first because I didn't want to endorse downloads I haven't tested, but it'll probably be useful going forward to distinguish between "rough" and "refined" LoRAs. Might write a script to collect the information automatically. Of note: I think @deep-diver also updated his weights to r=16 and q/k/v/o.

**Comment by deep-diver** [comment]
Yes just did today at https://huggingface.co/chansung/alpaca-lora-13b and will upload 30b version at https://huggingface.co/chansung/alpaca-lora-30b as well tomorrow. I simply used the same script as

```
python finetune.py \ --base_model='decapoda-research/llama-7b-hf' \ --num_epochs=10 \ --cutoff_len=512 \ --group_by_length \ --output_dir='./lora-alpaca' \ --lora_target_modules='[q_proj,k_proj,v_proj,o_proj]' \ --lora_r=16 \ --micro_batch_size=8
```

**Comment by deep-diver** [comment]
If you are curious, here is the playground with 13B model (ignore the wrong contents in the markdown saying 30B)

https://notebooksf.jarvislabs.ai/BuOu_VbEuUHb09VEVHhfnFq4-PMhBRVCcfHBRCOrq7c4O9GI4dIGoidvNf76UsRL/

**Comment by diegomontoya** [comment]
@AngainorDev  Without eval, how can you tell your model training is not just overshooting everything with too much training? During my testing with high epoch and 250k sized training data, eval became must worse and starts regressing after 2-3 epochs even through train/loss was still at steady level.  In my case, depending on size of training data size, high epochs is not the best option.

**Comment by tloen** [comment]
@diegomontoya The training code as provided has load_best_checkpoint set to True, which should pick the checkpoint with the lowest eval loss.

**Comment by diegomontoya** [comment]
@tloen  Yes, but @AngainorDev  provided the refined trained weights with ```--val_set_size=0``` which I assume will disable evaluation and thus my question on who he was able to determine the checkpoint he chose was the best one since no eval was generated? Maybe I am mistaken to what --val_set_size=0  means?

**Comment by deep-diver** [comment]
just uploaded fine-tuned 30B version. The final loss is as below
: `{'loss': 0.5584, 'learning_rate': 0.0, 'epoch': 9.99}`

here is the link
: https://huggingface.co/chansung/alpaca-lora-30b/tree/main

It was trained on A100 40G * 8 DGX workstation for about 32 hours. 

if there is a way to mark something like "this version is trained on the cleaned dataset(4/6/2022) with the latest known to be working better technique(lora_r, target_modules, epochs)"

**Comment by claysauruswrecks** [comment]
@AngainorDev - Are the evals you're talking about different than the kind mentioned here? https://github.com/tloen/alpaca-lora/issues/147

**Comment by AngainorDev** [comment]
These are generic evals, I'd want a dedicated alpaca style eval dataset, with instructions similar to (and different from) what alpaca training has.

**Comment by AngainorDev** [comment]
There is this repo, 
I tweaked the test script to work with our loras
https://github.com/manyoso/haltt4llm/pull/6

But this one mainly focuses on hallucinations with a specific multiplce choice template that is not known to Alpaca, so it has a hard time answering "IDK" or "None of the above".
Still a good move, but this only checks for factual knowledge, no other capabilities.
