### ISSUE TITLE
Fine-tuning based on alpaca-lora weights

### ISSUE THREAD

**Issue by ZJU-Fangyin** [tloen/alpaca-lora#284]
How to continue fine-tuning based on the provided `lora_weights = 'tloen/alpaca-lora-7b'`?
Should I modify the `finetune.py` file in this way?

```
    model = LlamaForCausalLM.from_pretrained(
        base_model,
        load_in_8bit=True,
        torch_dtype=torch.float16,
        device_map=device_map,
    )

    model = prepare_model_for_int8_training(model)

    # model = get_peft_model(model, config)
    model = PeftModel.from_pretrained(
        model,
        lora_weights = 'tloen/alpaca-lora-7b',
        torch_dtype = torch.float16,
        device_map = device_map,
    )
```

**Comment by AngainorDev** [comment]
Nothing to modify.

Just add `--resume_from_checkpoint='tloen/alpaca-lora-7b'` to the usual finetune config.

**Comment by AngainorDev** [comment]
You have to check the params used by the lora you start from.
Lora rank, alpha, layers to tune.
Then use the exact same in your own tuning.
There you used a rank 16 and try to tune it further with rank 8.

The original params are in the config json of the lora you use.
default 7b lora now is a rank 16 with 4 layers, no more the default config.

**Comment by ZJU-Fangyin** [comment]
@AngainorDev  Thank you very much for your patience in responding! The problem has been sorted out successfully.

**Comment by renmengjie7** [comment]
I have the same problem.
Where's the "continue_from_checkpoint" ? I can't find.

**Comment by renmengjie7** [comment]
Sorry. I just noticed the parameter name changed to resume_from_checkpoint.
