### ISSUE TITLE
adapter_model.bin not being updated and only 443 bytes after finetuning

### ISSUE THREAD

**Issue by danucalovj** [tloen/alpaca-lora#293]
Just finished training with a new dataset for a total of 1392 steps on 4x A6000 GPUs using the following parameters:

set WORLD_SIZE=4
set CUDA_VISIBLE_DEVICES=0,1,2,3
!torchrun --nproc_per_node=4 --master_port=1234 finetune.py \
--base_model ./llama-13b-hf \
--output_dir ./alpaca-lora-13b \
--group_by_length \
--lora_target_modules='[q_proj,k_proj,v_proj,o_proj]' \
--lora_r=16 \
--data-path alpaca_data_cleaned2.json \
--num_epochs 3 \
--cutoff_len=512 \
--micro_batch_size 16

Training finished fine, no errors or logs indicating any issues. Checkpoints were created with no issues. But the adapter_mode.bin never updated at the end of the training and instead I have a 443 byte file which when loaded through generate.py, gradio won't generate an output at all (also no errors, the counter just indefinitely runs).

Any clue? I'd provide logs, but there are no error logs.

Is there a way to either load the pytorch_model.bin directly through generate.py? Or, any way to convert my checkpoint into the adapter_model.bin format?

**Comment by x22x22** [comment]
me to

**Comment by x22x22** [comment]
> Just finished training with a new dataset for a total of 1392 steps on 4x A6000 GPUs using the following parameters:
> 
> set WORLD_SIZE=4 set CUDA_VISIBLE_DEVICES=0,1,2,3 !torchrun --nproc_per_node=4 --master_port=1234 finetune.py --base_model ./llama-13b-hf --output_dir ./alpaca-lora-13b --group_by_length --lora_target_modules='[q_proj,k_proj,v_proj,o_proj]' --lora_r=16 --data-path alpaca_data_cleaned2.json --num_epochs 3 --cutoff_len=512 --micro_batch_size 16
> 
> Training finished fine, no errors or logs indicating any issues. Checkpoints were created with no issues. But the adapter_mode.bin never updated at the end of the training and instead I have a 443 byte file which when loaded through generate.py, gradio won't generate an output at all (also no errors, the counter just indefinitely runs).
> 
> Any clue? I'd provide logs, but there are no error logs.
> 
> Is there a way to either load the pytorch_model.bin directly through generate.py? Or, any way to convert my checkpoint into the adapter_model.bin format?

you can try change peft version
```bash
pip uninstall peft
pip install git+https://github.com/huggingface/peft.git@e536616888d51b453ed354a6f1e243fecb02ea08
```
That's how I solved it.

**Comment by danucalovj** [comment]
Uninstalling peft and reinstalling did the trick, thanks!

**Comment by griff4692** [comment]
> 

Is there a way to load the checkpoint weights directly without using "adapter_model.bin"?

ls -la ./
```
-rw-r--r-- 1 ga2530 nlp  365 Apr  9 08:23 adapter_config.json
-rw-r--r-- 1 ga2530 nlp  443 Apr  9 08:23 adapter_model.bin
drwxr-xr-x 2 ga2530 nlp 4096 Apr 12 04:56 checkpoint-1000
```

ls -la checkpoint-1000

```
-rw-r--r-- 1 ga2530 nlp 33661637 Apr 12 04:56 optimizer.pt
-rw-r--r-- 1 ga2530 nlp 16822989 Apr 12 04:56 pytorch_model.bin
-rw-r--r-- 1 ga2530 nlp    17641 Apr 12 04:56 rng_state.pth
-rw-r--r-- 1 ga2530 nlp      557 Apr 12 04:56 scaler.pt
-rw-r--r-- 1 ga2530 nlp      627 Apr 12 04:56 scheduler.pt
-rw-r--r-- 1 ga2530 nlp   120184 Apr 12 04:56 trainer_state.json
-rw-r--r-- 1 ga2530 nlp     3579 Apr 12 04:56 training_args.bin
```

Fine-tuning took 3 days so hoping not to have re-do it.  otherwise, I will uninstall and re-install peft

**Comment by nkjulia** [comment]
> > 
> 
> Is there a way to load the checkpoint weights directly without using "adapter_model.bin"?
> 
> ls -la ./
> 
> ```
> -rw-r--r-- 1 ga2530 nlp  365 Apr  9 08:23 adapter_config.json
> -rw-r--r-- 1 ga2530 nlp  443 Apr  9 08:23 adapter_model.bin
> drwxr-xr-x 2 ga2530 nlp 4096 Apr 12 04:56 checkpoint-1000
> ```
> 
> ls -la checkpoint-1000
> 
> ```
> -rw-r--r-- 1 ga2530 nlp 33661637 Apr 12 04:56 optimizer.pt
> -rw-r--r-- 1 ga2530 nlp 16822989 Apr 12 04:56 pytorch_model.bin
> -rw-r--r-- 1 ga2530 nlp    17641 Apr 12 04:56 rng_state.pth
> -rw-r--r-- 1 ga2530 nlp      557 Apr 12 04:56 scaler.pt
> -rw-r--r-- 1 ga2530 nlp      627 Apr 12 04:56 scheduler.pt
> -rw-r--r-- 1 ga2530 nlp   120184 Apr 12 04:56 trainer_state.json
> -rw-r--r-- 1 ga2530 nlp     3579 Apr 12 04:56 training_args.bin
> ```
> 
> Fine-tuning took 3 days so hoping not to have re-do it. otherwise, I will uninstall and re-install peft
you can try replace the file "adapter_model" by   "pytorch_model.bin" in checkpoint-1000.

**Comment by Dorys221** [comment]
Same issue. Do I have to restart the training completely with the correct version installed or I can like overwrite the current adapter_model.bin file with some script?

**Comment by tentatshu** [comment]
per @nkjulia, just replace "adapter_model.bin" with a "pytorch_model.bin" from one of the checkpoints. was a quick workable solution for me.

**Comment by yuanzhedong** [comment]
Does anyone know why the official ckpt is 67MB but the one I got is ~17MB?

https://huggingface.co/tloen/alpaca-lora-7b/tree/main

<img width="459" alt="image" src="https://github.com/tloen/alpaca-lora/assets/5069709/6428bbf1-3467-4947-aac4-b976acb7aaba">

**Comment by ngoanpv** [comment]
@yuanzhedong I had the same problem with the model size is ~17M and it cannot generate the response. Do you have any solution?

**Comment by kocoten1992** [comment]
> Does anyone know why the official ckpt is 67MB but the one I got is ~17MB?
> 
> https://huggingface.co/tloen/alpaca-lora-7b/tree/main
> 
> <img alt="image" width="459" src="https://user-images.githubusercontent.com/5069709/239698380-6428bbf1-3467-4947-aac4-b976acb7aaba.png">

That because they use this config:

```
    --lora_target_modules='[q_proj,k_proj,v_proj,o_proj]' \
    --lora_r=16 \
```

see https://huggingface.co/tloen/alpaca-lora-7b

**Comment by yuanzhedong** [comment]
I see, thanks, for more context
https://github.com/tloen/alpaca-lora/issues/233#issuecomment-1492448528

**Comment by cmosguy** [comment]
Hello - so I tried using 
```git+https://github.com/huggingface/peft.git@4c611f4
```
I am still getting 443 file size for my `adapter_model.bin` for each checkpoint.  I have my gist here of the script I am running:
https://gist.github.com/cmosguy/4b5052507191200397c551fc24853ef0

Can someone tell me what I could be doing incorrectly here that help resolve the issue? I cannot quite understand why for the final saving the the model it does not update the lora weights.

Cheers!
Adam

**Comment by scissorstail** [comment]
Please comment out this section in the training script. It seems to work then.

```
# old_state_dict = model.state_dict
# model.state_dict = (
#     lambda self, *_, **__: get_peft_model_state_dict(self, old_state_dict())
# ).__get__(model, type(model))
```
