### ISSUE TITLE
error when run finetune.py

### ISSUE THREAD

**Issue by mazzzystar** [tloen/alpaca-lora#294]
When I run `python finetune.py`, it will first shows error like this:
```bash
  File "/home/ubuntu/miniconda3/envs/lora/lib/python3.10/site-packages/bitsandbytes/functional.py", line 1505, in get_colrow_absmax
    lib.cget_col_row_stats(ptrA, ptrRowStats, ptrColStats, ptrNnzrows, ct.c_float(threshold), rows, cols)
  File "/home/ubuntu/miniconda3/envs/lora/lib/python3.10/ctypes/__init__.py", line 387, in __getattr__
    func = self.__getitem__(name)
  File "/home/ubuntu/miniconda3/envs/lora/lib/python3.10/ctypes/__init__.py", line 392, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /home/ubuntu/miniconda3/envs/lora/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so: undefined symbol: cget_col_row_stats
```

Then I tried as this: https://github.com/TimDettmers/bitsandbytes/issues/156#issuecomment-1474056975

The error then become:
```bash
Loading checkpoint shards:   0%|                                                                                              | 0/33 [00:00<?, ?it/s]
Error named symbol not found at line 508 in file /mmfs1/gscratch/zlab/timdettmers/git/bitsandbytes/csrc/ops.cu
```
I'm using `Python 3.10` + `CUDA 11.7`.

**Comment by ParaNoth** [comment]
Which architecture graphics card are you using? If your graphics card's architecture is not Turing or Ampere, you should use `libbitsandbytes_cuda{your_cuda_version}_nocublaslt.so` instead of `libbitsandbytes_cuda{your_cuda_version}.so`

**Comment by mazzzystar** [comment]
@ParaNoth Thank you very much!

My graphics is `NVIDIA V100`, I figured out it was `Volta` architecture. I've changed to `libbitsandbytes_cuda{cuda_version}_nocublaslt.so` and it works!

<img width="1189" alt="image" src="https://user-images.githubusercontent.com/6824141/230898958-7ad5ffcf-de99-4d15-9a41-0c8fe7207b6b.png">

**Comment by herobrine19** [comment]
It works same to me! Thank you!
