### ISSUE TITLE
Training on custom dataset

### ISSUE THREAD

**Issue by usmanxia** [tloen/alpaca-lora#295]
Can we train the model on custom dataset from scratch?

**Comment by ElleLeonne** [comment]
Of course.
1) make a new prompt
2) ensure your data is a list of dictionaries
3) ensure it contains at least an instruction and output key.

Overhauling the prompter requires a bit more work, but is doable, if you need more exotic data or something.

**Comment by usmanxia** [comment]
Thanx @ElleLeonne
Just one linked question.

The finetuning is done on a base model

python finetune.py \
    --base_model 'decapoda-research/llama-7b-hf' \
    --data_path 'yahma/alpaca-cleaned' \
    --output_dir './lora-alpaca'


So the conversational part can be done from scratch but LLM would remain llama, right?

Can we also replace it with LLM trained on custom dataset?

**Comment by ElleLeonne** [comment]
So a LoRA adapter learns a representation of the base model. If the base model is the body, then the LoRA adapter is the head on top of the body. The body still stays the same unless you merge the weights or something.

**Comment by usmanxia** [comment]
So with analogy, if I want to train the head  (LoRa adapter) on financial data, but the body is already trained on openwebtext, won't the body skew the output of the head by injecting it's learnt patterns?

**Comment by ElleLeonne** [comment]
Yes, it probably would. You could potentially offset this imbalance by increasing the rank and epoch count, or you could just repeatedly train adapters and merge them back into the body to "move" the base model closer to your goal.

**Comment by usmanxia** [comment]
Thanx @ElleLeonne, appreciate your time and guidance.
