### ISSUE TITLE
Newest peft update breaks load_from_checkpoint

### ISSUE THREAD

**Issue by ElleLeonne** [tloen/alpaca-lora#297]
https://github.com/huggingface/peft/issues/285

Still trying to sort out how to proceed on my own branch, but I figured I'd bring it up here too, since it'll invalidate the codebase, and maybe more eyes will help.

**Comment by diegomontoya** [comment]
Ref issue as both are related to same core cause. Frankly, this peft/transformer breakage in the last 2-7 days has been a disaster for llama adopters. The entire chain of the llama code/training process in all projects is either broken or no longer forward/cross compatible with the forthcoming stable 4.28 transformer release.

https://github.com/tloen/alpaca-lora/issues/298
