### ISSUE TITLE
export_hf not merging weights

### ISSUE THREAD

**Issue by thistleknot** [tloen/alpaca-lora#298]
I ran through the code line by line and the second merge fails.  Used this model as the base_model
'decapoda-research/llama-7b-hf'

**Comment by ElleLeonne** [comment]
Confirmed w/ manually converted weights & new tokenizer.

As of now, the only way to preserve fine-tuning between sessions is to have resume_from_checkpoint target the weights folder, without a checkpoint supplied.

Seems like transformers and peft both pushed out major updates at the same time.

**Comment by thistleknot** [comment]
Do you have an example of resume_from_checkpoint

**Comment by ElleLeonne** [comment]
https://github.com/huggingface/peft/issues/285

I posted mine on the peft repo.

The layers don't seem to be merging properly.

**Comment by diegomontoya** [comment]
Just ran into this myself even though I made sure all the training and base model are already compliant with the new LlamaTokenizerFast from transformer[head].

`As of now, the only way to preserve fine-tuning between sessions is to have resume_from_checkpoint target the weights folder, without a checkpoint supplied.`

@ElleLeonne  What do you mean by resume_from_checkpoint targeting the weights folder and not a checkpoint? The lora-train checkpoints does contain the delta-weights in format of python_model.bin. How are you currently forcing the Lora trained deltas to apply? Thanks.

**Comment by ElleLeonne** [comment]
>What do you mean by resume_from_checkpoint targeting the weights folder and not a checkpoint? The lora-train checkpoints does contain the delta-weights in format of python_model.bin. How are you currently forcing the Lora trained deltas to apply? Thanks.

Loading just the adapter before training, though the results seem pretty bad.

**Comment by pacman100** [comment]
Hello @thistleknot,

With recent changes, all you need to do to merge and get back the transformers models is `model = model.merge_and_unload()`. link to the colab notebook showing how to do this for your exact usecase: https://colab.research.google.com/drive/1k4abYWhXOThdNFpniay4BtnEo-4cpnaO?usp=sharing

```

import torch
from peft import PeftModel
import transformers
import os, time
import tempfile

#assert ("LlamaTokenizer" in transformers._import_structure["models.llama"]), "LLaMA is now in HuggingFace's main branch.\nPlease reinstall it: pip uninstall transformers && pip install git+https://github.com/huggingface/transformers.git"
from transformers import LlamaTokenizer, LlamaForCausalLM, GenerationConfig

tokenizer = LlamaTokenizer.from_pretrained("decapoda-research/llama-7b-hf")

BASE_MODEL = "decapoda-research/llama-7b-hf"
LORA_WEIGHTS = "tloen/alpaca-lora-7b"

force_cpu = False

if torch.cuda.is_available() and not force_cpu:
    device = "cuda"
    print("Video memory available:", torch.cuda.get_device_properties(0).total_memory / 1024 / 1024, "MBs")
else:
    device = "cpu"
print("Compute device is:", device)

print("Loading model with selected weights ...")

if device == "cuda":
    
    print("model on cuda")
    
    model = LlamaForCausalLM.from_pretrained(
        BASE_MODEL,
        load_in_8bit=False,
        torch_dtype=torch.float16,
        device_map="auto",
        offload_folder="offload", 
    )
    
    model = PeftModel.from_pretrained(
        model, 
        LORA_WEIGHTS, 
        torch_dtype=torch.float16,
        device_map="auto",
        offload_folder="offload", 
        
    )

model = model.merge_and_unload()
model.save_pretrained("english_alpaca_lora_7b")
```

<img width="1500" alt="Screenshot 2023-04-09 at 11 24 07 AM" src="https://user-images.githubusercontent.com/13534540/230756979-cf6c9709-c358-43b8-90a1-866ea4a2b21b.png">

**Comment by diegomontoya** [comment]
@pacman100 

I am not getting the correct merged model output. Instead I get an adapter json file and an almost empty adapter_model.bin. What could be causing this for my mode?

```
import os

import torch
from peft import PeftModel
from transformers import AutoModelForCausalLM

BASE_MODEL = "/root/meta-llama-30b-hf"
LORA_ADAPTER = "/root/llama-30b-gpt4-52k-gram-9k"

print("loading base\n")
model = AutoModelForCausalLM.from_pretrained(
    BASE_MODEL,
    load_in_8bit=False,
    torch_dtype=torch.float16,
    device_map={"": "cpu"},
)


print("loading lora\n")
model = PeftModel.from_pretrained(
    model,
    LORA_ADAPTER,
    device_map={"": "cpu"},
    torch_dtype=torch.float16,
)


print("merging lora with base\n")
model.merge_and_unload()


print("save model\n")
model.save_pretrained("/root/llama-30b-gpt4-32k-gram-9k-merged-NEW2")
```

![image](https://user-images.githubusercontent.com/417764/230761243-9ab85b9f-b1fa-44fa-8b50-4d4ee83587f6.png)

**Comment by pacman100** [comment]
Hello @diegomontoya, you need to do `model = model.merge_and_unload()`, i.e., the output needs to be assigned.

**Comment by thistleknot** [comment]
config = AutoConfig.from_pretrained("/mnt/distvol/english_alpaca_lora_7b/")
			model_with_lora = AutoModelForCausalLM.from_pretrained("/mnt/distvol/offload/", config=config)

**Comment by thistleknot** [comment]
https://gist.github.com/thistleknot/66bddfee985e3039dd06aa312969222c
