### ISSUE TITLE
Tokenizer class function warning

### ISSUE THREAD

**Issue by gururise** [tloen/alpaca-lora#31]
Getting the following error with the latest commit (even after uninstalling and re-installing transformers from git):
```
The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'LLaMATokenizer'. 
The class this function is called from is 'LlamaTokenizer'.
```

I also tried force_download=True and still get the error.

**Comment by tloen** [comment]
This is expected behavior; the class is renamed in huggingface/transformers but not on the Hub.

The warning should be safe to ignore.
