### ISSUE TITLE
Want train more parameters during lora finetuning

### ISSUE THREAD

**Issue by LiuPearl1** [tloen/alpaca-lora#312]
When finetuning the model, we set lora_target_modules = ['q_proj','k_proj','v_proj','o_proj']. If I want to train more parameters, like feed-forward layer or layernorm, how should I set lora_target_modules?

**Comment by ElleLeonne** [comment]
While I'd like to hear more on this myself, if you're just after parameters, you could increase rank, which is the dimensionality of the adapter.

**Comment by LiuPearl1** [comment]
@ElleLeonne Thank you~ I wonder if I can finetune layernorm, embedding or feed-forward layer. How to set these parameters?
