### ISSUE TITLE
AttributeError while export hf model

### ISSUE THREAD

**Issue by yangp725** [tloen/alpaca-lora#349]
> AttributeError: 'LlamaForCausalLM' object has no attribute 'merge_and_unload'

What's your torch, transformers and peft version?

**Comment by TheBloke** [comment]
Hi

I have this exact issue. Did you fix it?  Could you tell me how please?

I am using PyTorch 2.0.0, and I have tried peft and transformers from normal pip:
`pip3 install peft transformers`

And I have also tried installing the latest code from Github:
`pip3 install git+https://github.com/huggingface/peft.git git+https://github.com/huggingface/transformers`

Any advice would be appreciated!

**Comment by kenlinkenlin21** [comment]
> Hi @yangp725
> 
> I have this exact issue running https://github.com/tloen/alpaca-lora/blob/main/export_hf_checkpoint.py. Did you fix it? Could you tell me how please?
> 
> I am using PyTorch 2.0.0, and I have tried peft and transformers from normal pip: `pip3 install peft transformers`
> 
> And I have also tried installing the latest code from Github: `pip3 install git+https://github.com/huggingface/peft.git git+https://github.com/huggingface/transformers`
> 
> Any advice would be appreciated!
> 
> Here's the full errors when I run the script:
> 
> ```
> Loading checkpoint shards: 100%
> 3/3 [00:19<00:00, 5.99s/it]
> 
> ╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
> │ /usr/local/lib/python3.9/dist-packages/peft/peft_model.py:287 in __getattr__                     │
> │                                                                                                  │
> │    284 │   │   """                                                                               │
> │    285 │   │   Forward pass of the model.                                                        │
> │    286 │   │   """                                                                               │
> │ ❱  287 │   │   return self.get_base_model()(*args, **kwargs)                                     │
> │    288 │                                                                                         │
> │    289 │   @contextmanager                                                                       │
> │    290 │   def disable_adapter(self):                                                            │
> │                                                                                                  │
> │ /usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py:1614 in __getattr__            │
> │                                                                                                  │
> │   1611 │   │   │   modules = self.__dict__['_modules']                                           │
> │   1612 │   │   │   if name in modules:                                                           │
> │   1613 │   │   │   │   return modules[name]                                                      │
> │ ❱ 1614 │   │   raise AttributeError("'{}' object has no attribute '{}'".format(                  │
> │   1615 │   │   │   type(self).__name__, name))                                                   │
> │   1616 │                                                                                         │
> │   1617 │   def __setattr__(self, name: str, value: Union[Tensor, 'Module']) -> None:             │
> ╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
> AttributeError: 'PeftModelForCausalLM' object has no attribute 'merge_and_unload'
> 
> During handling of the above exception, another exception occurred:
> 
> ╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
> │ /usr/local/lib/python3.9/dist-packages/peft/tuners/lora.py:204 in __getattr__                    │
> │                                                                                                  │
> │   201 │   │   │   │   │   │   │   │   warnings.warn(                                             │
> │   202 │   │   │   │   │   │   │   │   │   "fan_in_fan_out is set to True but the target module   │
> │   203 │   │   │   │   │   │   │   │   │   "Setting fan_in_fan_out to False."                     │
> │ ❱ 204 │   │   │   │   │   │   │   │   )                                                          │
> │   205 │   │   │   │   │   │   │   │   kwargs["fan_in_fan_out"] = lora_config.fan_in_fan_out =    │
> │   206 │   │   │   │   │   │   elif isinstance(target, Conv1D):                                   │
> │   207 │   │   │   │   │   │   │   in_features, out_features = (                                  │
> │                                                                                                  │
> │ /usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py:1614 in __getattr__            │
> │                                                                                                  │
> │   1611 │   │   │   modules = self.__dict__['_modules']                                           │
> │   1612 │   │   │   if name in modules:                                                           │
> │   1613 │   │   │   │   return modules[name]                                                      │
> │ ❱ 1614 │   │   raise AttributeError("'{}' object has no attribute '{}'".format(                  │
> │   1615 │   │   │   type(self).__name__, name))                                                   │
> │   1616 │                                                                                         │
> │   1617 │   def __setattr__(self, name: str, value: Union[Tensor, 'Module']) -> None:             │
> ╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
> AttributeError: 'LoraModel' object has no attribute 'merge_and_unload'
> 
> During handling of the above exception, another exception occurred:
> 
> ╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
> │ in <cell line: 39>:39                                                                            │
> │                                                                                                  │
> │ /usr/local/lib/python3.9/dist-packages/peft/peft_model.py:289 in __getattr__                     │
> │                                                                                                  │
> │    286 │   │   """                                                                               │
> │    287 │   │   return self.get_base_model()(*args, **kwargs)                                     │
> │    288 │                                                                                         │
> │ ❱  289 │   @contextmanager                                                                       │
> │    290 │   def disable_adapter(self):                                                            │
> │    291 │   │   """                                                                               │
> │    292 │   │   Disables the adapter module.                                                      │
> │                                                                                                  │
> │ /usr/local/lib/python3.9/dist-packages/peft/tuners/lora.py:206 in __getattr__                    │
> │                                                                                                  │
> │   203 │   │   │   │   │   │   │   │   │   "Setting fan_in_fan_out to False."                     │
> │   204 │   │   │   │   │   │   │   │   )                                                          │
> │   205 │   │   │   │   │   │   │   │   kwargs["fan_in_fan_out"] = lora_config.fan_in_fan_out =    │
> │ ❱ 206 │   │   │   │   │   │   elif isinstance(target, Conv1D):                                   │
> │   207 │   │   │   │   │   │   │   in_features, out_features = (                                  │
> │   208 │   │   │   │   │   │   │   │   target.weight.ds_shape if hasattr(target.weight, "ds_sha   │
> │   209 │   │   │   │   │   │   │   )                                                              │
> │                                                                                                  │
> │ /usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py:1614 in __getattr__            │
> │                                                                                                  │
> │   1611 │   │   │   modules = self.__dict__['_modules']                                           │
> │   1612 │   │   │   if name in modules:                                                           │
> │   1613 │   │   │   │   return modules[name]                                                      │
> │ ❱ 1614 │   │   raise AttributeError("'{}' object has no attribute '{}'".format(                  │
> │   1615 │   │   │   type(self).__name__, name))                                                   │
> │   1616 │                                                                                         │
> │   1617 │   def __setattr__(self, name: str, value: Union[Tensor, 'Module']) -> None:             │
> ╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
> AttributeError: 'LlamaForCausalLM' object has no attribute 'merge_and_unload'
> ```

I also got this error, do you solve this problem?

**Comment by WhuRan** [comment]
pip install git+https://github.com/huggingface/peft.git
Update to the latest package
