### ISSUE TITLE
Finetuning saves a 443 byte adapter_model.bin

### ISSUE THREAD

**Issue by likaixin2000** [tloen/alpaca-lora#363]
I am trying to finetune a Llama model. The finetuning process runs smoothly, but the resulting `adapter_model.bin` is only 443 bytes. Does anybody know why is this happening?

**Comment by danucalovj** [comment]
See:

https://github.com/tloen/alpaca-lora/issues/293

**Comment by lywinged** [comment]
> I am trying to finetune a Llama model. The finetuning process runs smoothly, but the resulting `adapter_model.bin` is only 443 bytes. Does anybody know why is this happening?

Update your PEFT, they fixed the bug yesterday.

**Comment by ningzichun** [comment]
With latest code(8bb8579e403dc78e37fe81ffbb253c413007323f) and requirements.txt, it still produces 443 byte adapter_model.bin, I still need to refer to #293 to install certain version of peft or use the modified finetune.py #359  to produce correct adapter_model.bin.

**Comment by lywinged** [comment]
> 
Is your peft 0.3.0?  I uninstalled then updated, it works for me.

**Comment by nkjulia** [comment]
> your peft 0.3.0? I uninstalled then

i reinstall the PEFT 0.3.0.dev0  from git soure code,the problem still exists.

**Comment by xunushan** [comment]
I have also updated peft to 0.3.0.dev0 ,  but I encountered the same issue.

**Comment by lywinged** [comment]
> 

Maybe that’s a new issue, I launched a new Google colab and install 0.3.0 dev0 and it works.

**Comment by lywinged** [comment]
The problem is still there, we have to use the old version.

**Comment by likaixin2000** [comment]
> The problem is still there, we have to use the old version.

Which version of peft are you using? For lower versions, there is another problem that causes the GPU to OOM when saving checkpoints. It seems only a few commits of peft can work perfectly, but I can't locate them...

**Comment by lywinged** [comment]
> > The problem is still there, we have to use the old version.
> 
> Which version of peft are you using? For lower versions, there is another problem that causes the GPU to OOM when saving checkpoints. It seems only a few commits of peft can work perfectly, but I can't locate them...

git+https://github.com/huggingface/peft.git@e536616888d51b453ed354a6f1e243fecb02ea08
I'm using this one.

**Comment by likaixin2000** [comment]
> 

It works! Thank you!

**Comment by abdoelsayed2016** [comment]
> > > The problem is still there, we have to use the old version.
> > 
> > 
> > Which version of peft are you using? For lower versions, there is another problem that causes the GPU to OOM when saving checkpoints. It seems only a few commits of peft can work perfectly, but I can't locate them...
> 
> git+https://github.com/huggingface/peft.git@e536616888d51b453ed354a6f1e243fecb02ea08 I'm using this one.

after i installed the model output is 
![image](https://github.com/tloen/alpaca-lora/assets/27821589/64fc244d-fcc8-485c-b48c-4a26fc96d60c)


i saw that model generate the output of  [7,7,7,7,7,7,7,7,7,7,7,7,7,77,7,7,7,7,7,7,7,7,7,7,77,7,7,7,7,7,7,7,7]

anyone solve this problem
