### ISSUE TITLE
How to see all possible lora_target_modules?

### ISSUE THREAD

**Issue by zolastro** [tloen/alpaca-lora#373]
I was wondering where you can find more info about the `lora_target_modules`. So far, I've seen that the default ones are  `["q_proj",v_proj"]`, could you please give more insight on where to find them and how to use them? 

Thanks in advance!

**Comment by zolastro** [comment]
I just found that these are references to the fields in `model.named_modules()`. However, I wonder if more insight in which of these modules should we train and why.

**Comment by pan365wang** [comment]
我也想知道

**Comment by ElleLeonne** [comment]
> I just found that these are references to the fields in `model.named_modules()`. However, I wonder if more insight in which of these modules should we train and why.

Oh yes, so I discovered some more.

lm_head, and wte for attention heads and text embedding layer respectively.

Also discovered that you can just pass in model.layer too, which works so long as it's a supported type.
