### ISSUE TITLE
fine tune llama-7b-hf    after finished  the adapter_modle.bin file only 4kb

### ISSUE THREAD

**Issue by elven2016** [tloen/alpaca-lora#390]
Please help,
I used 2*V100 32GB finetune llama-7b-hf model,  I have tryed  more than 3times, when fineshed ,the adapter_model.bin file only 4k
the first time，used the default parameter
![image](https://user-images.githubusercontent.com/16677082/234459036-29c2d4d1-4c24-4f80-b128-940670a8c17b.png)
the second time，used the default parameter
![image](https://user-images.githubusercontent.com/16677082/234459285-a2ab1292-5bdf-4780-a197-4c65d2187823.png)
the third time，used the  parameter in the model Card decription  of tloen/alpaca-lora-7b  of Huggingface site
![image](https://user-images.githubusercontent.com/16677082/234458712-04fa5c73-8caf-4128-a12f-09bd80606b3c.png)
I'm new in this filed , I'm  not sure if  this result is ok or not  , but the official bin file is 67M, 
![image](https://user-images.githubusercontent.com/16677082/234460624-14c5abe1-5029-4166-9552-c3741c98d216.png)

**Comment by Sissel-Wu** [comment]
I encountered the same issue and fixed it with the following solution:

https://github.com/tloen/alpaca-lora/issues/326#issuecomment-1507946790

**Comment by CharlesLiu7** [comment]
due to the `peft` version change, the `model.save_pretrained` in `finetune.py` failed to save `adapter_model.bin` . the simplest way is to use the adapter in checkpoint, which can do 
```
mv checkpoint-xxx/pytorch_model.bin adapter_model.bin
```

**Comment by elven2016** [comment]
> due to the `peft` version change, the `model.save_pretrained` in `finetune.py` failed to save `adapter_model.bin` . the simplest way is to use the adapter in checkpoint, which can do
> 
> ```
> mv checkpoint-xxx/pytorch_model.bin adapter_model.bin
> ```
thanks，it works

**Comment by Risingabhi** [comment]
@elven2016 i have saved the adapter_model.bin , its size is very small, when i use checkpoint ....py file in repo [ meant to combine base model with adapeter, i was hoping to get  a new file which should be close to 3.92 GB+, but here again i see a very small file. Am i right in thinking this, or i am doing it wrong? please confirm.

**Comment by elven2016** [comment]
> @elven2016 i have saved the adapter_model.bin , its size is very small, when i use checkpoint ....py file in repo [ meant to combine base model with adapeter, i was hoping to get a new file which should be close to 3.92 GB+, but here again i see a very small file. Am i right in thinking this, or i am doing it wrong? please confirm.

it's not right，your issue is the same as  #293  you can try it， it's the problemof peft，just：pip uninstall peft -y
pip install git+https://github.com/huggingface/peft.git@e536616888d51b453ed354a6f1e243fecb02ea08  
after reinstall this version peft，then start train it again

**Comment by cxfcxf** [comment]
although you closed this issue but for the new comer, instead of train from beginning
I had same issue, none of people mentioned this, you can actually resume from the checkpoint by
run the same command and do
```bash
python finetune.py --base_model 'decapoda-research/llama-7b-hf' --data_path 'yahma/alpaca-cleaned' --output_dir './lora-alpaca_1' --resume_from_checkpoint 'lora-alpaca/checkpoint-1000'
```

**Comment by larawehbe** [comment]
Hello
after a succesful finetuning,the file containing adapter.bin becomes the new weights that i need to use?
how to convert them o consolidated.00.bin and then quantize it ?
