### ISSUE TITLE
 CUDA out of memory error.  How to calculate or what am I doing wrong?

### ISSUE THREAD

**Issue by sytandas** [tloen/alpaca-lora#442]
Hello, Sorry for asking basic question. I have RTX 2070 and while executing finetune.py with vicuna-7B model.  I am getting this error:: 
OutOfMemoryError: CUDA out of memory. Tried to allocate 500.00 MiB (GPU 0; 7.78 
GiB total capacity; 6.68 GiB already allocated; 228.19 MiB free; 6.98 GiB 
reserved in total by PyTorch) If reserved memory is >> allocated memory try 
setting max_split_size_mb to avoid fragmentation.  See documentation for Memory 
Management and PYTORCH_CUDA_ALLOC_CONF

Thanks in advance.

**Comment by yyhycx** [comment]
The memory of 2070 is too small, you need about 12g of memory
