### ISSUE TITLE
安装依赖时候发生错误

### ISSUE THREAD

**Issue by donglc20** [tloen/alpaca-lora#491]
![image](https://github.com/tloen/alpaca-lora/assets/125566105/bcfe2449-e93a-4e25-a1da-c3918e9cc893)
Collecting git+https://github.com/huggingface/peft.git (from -r requirements.txt (line 9))
  Cloning https://github.com/huggingface/peft.git to /tmp/pip-req-build-rvzurjqe
  Running command git clone --filter=blob:none --quiet https://github.com/huggingface/peft.git /tmp/pip-req-build-rvzurjqe
  fatal: unable to access 'https://github.com/huggingface/peft.git/': Failed to connect to github.com port 443: Connection timed out
  error: subprocess-exited-with-error

  × git clone --filter=blob:none --quiet https://github.com/huggingface/peft.git /tmp/pip-req-build-rvzurjqe did not run successfully.
  │ exit code: 128
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git clone --filter=blob:none --quiet https://github.com/huggingface/peft.git /tmp/pip-req-build-rvzurjqe did not run successfully.
│ exit code: 128
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by BaoBaoGitHub** [comment]
请问你是怎么解决的？
我的服务器没有代理。

**Comment by BaoBaoGitHub** [comment]
已解决，解决方案是使用sudo权限配置/etc/hosts文件，具体请参考
https://github.com/521xueweihan/GitHub520 （记得备份一下hosts）。

**Comment by hexin1136** [comment]
> 已解决，解决方案是使用sudo权限配置/etc/hosts文件，具体请参考 https://github.com/521xueweihan/GitHub520 （记得备份一下hosts）。
Thank you very much for successfully resolving the issue
