### ISSUE TITLE
Does it work with multi-gpu training or accelearate?

### ISSUE THREAD

**Issue by deep-diver** [tloen/alpaca-lora#5]
First of all, thanks for building this up so quickly!
I really appreciate your hard work.

I was wondering if this code works w/o 8-bit quantization in general since it uses HuggingFace's common interface

**Comment by tloen** [comment]
I believe so! Just comment out the 8bit lines in fintune.py. Unfortunately I think PEFT will import bitsandbytes anyways so it still should be installed
