### ISSUE TITLE
Run alpaca-lora without going through the website 

### ISSUE THREAD

**Issue by EnzoDeg40** [tloen/alpaca-lora#510]
Is it possible to execute the base model and the adapter without going through the website (generate.py) but directly on the command line? Or does the local web interface have an API?
My goal is to call alpaca-lora model with my script python capable of doing text-to-speech and speech-to-text.

**Comment by matthiasgeihs** [comment]
Have a look at file `generate.py`.
It has an example of how to run inference directly without the Gradio interface.
https://github.com/tloen/alpaca-lora/blob/8bb8579e403dc78e37fe81ffbb253c413007323f/generate.py#L200-L213

**Comment by EnzoDeg40** [comment]
Ok thank you very much, I also didn't understand that the web interface (`gr.Interface`) was blocking the execution of the script
