### ISSUE TITLE
Memory usage not stable when switch to validation [DDP mode]

### ISSUE THREAD

**Issue by timothylimyl** [tloen/alpaca-lora#512]
During training, it does not go out of memory (OOM) but it will after validation.  This is obviously an unexpected behaviour. I have tested it for a few runs and it goes OOM every-time after validation.

My current workaround is to not do validation. I think this repo has some issue with multi-gpu training, it's been very buggy.

**Comment by timothylimyl** [comment]
Update: Realised that it is actually the saving step that is causing it.

**Comment by Linxyhaha** [comment]
> Update: Realised that it is actually the saving step that is causing it.

Hi, may I know how you set the saving step to solve the OOM issue?

**Comment by timothylimyl** [comment]
sorry @Linxyhaha , I forgot what I did but it could be that the repo does not take care of the save and eval steps properly [when i was using it previously]. If you are facing this issue, please raise a new issue as your issue could different than mine.
