### ISSUE TITLE
How to combine: base model + trained lora back to HF model?

### ISSUE THREAD

**Issue by baleksey** [tloen/alpaca-lora#53]
I've just played with [4bit quantization ](https://github.com/qwopqwop200/GPTQ-for-LLaMa) and it works really good. Much faster loading and inference time, ability to load much bigger model on GPU without quality degradation.  It's just like magic.

But in order to make quantized lora-trained model I need to combine somehow base HF + trained Lora and get new model in HF format. This new model can be quantized with GPTQ-for-LLaMa script. 

Here is a [someones guide](https://rentry.org/llama-tard-v2) for 4bit LLAMA if you want to try

Can anybody help?

**Comment by tloen** [comment]
https://github.com/tloen/alpaca-lora/blob/main/export_hf_checkpoint.py

**Comment by HaniItani** [comment]
Hello @tloen ,

I'm getting the following error when I load the huggingface checkpoint to the huggingface LlamaForCausalLM: `ValueError: weight is on the meta device, we need a `value` to put in on 0.` I made sure that all generate .bin files are on the cpu. Any idea what might be causing this issue?

Best regards,
Hani

**Comment by tloen** [comment]
Are you running the latest version of the code?

**Comment by HaniItani** [comment]
@tloen , sorry, just pulled, it works now. Thank you very much for sharing your work! Many thanks!

Best regards,
Hani

**Comment by cnmoro** [comment]
maybe a stupid question, but how can I use the quantized alpaca-lora model, and run inference with both parameters (input AND instruction) ?
