### ISSUE TITLE
webnovel_cn dataset release.（开源中文小说数据集）

### ISSUE THREAD

**Issue by ZhengJun-AI** [tloen/alpaca-lora#541]
To further improve the ability of LLM to generate Chinese novels, I have collect a dataset of Chinese instructions that can be used to train novel generation.
The full dataset contains approximately **21.7M** pieces of data, because the full dataset is too large, only a subset containing **50k** pieces of data is hosted on huggingface, see details
https://huggingface.co/datasets/zxbsmk/webnovel_cn

# Example usage
```
python finetune.py \
    --base_model 'elinas/llama-7b-hf-transformers-4.29' \
    --data_path 'zxbsmk/webnovel_cn' \
    --output_dir './lora-alpaca'
```

**Comment by meareabc** [comment]
感谢分享，我准备拿去GLM2的微调，请问是否可以

**Comment by ZhengJun-AI** [comment]
> 感谢分享，我准备拿去GLM2的微调，请问是否可以

当然可以。开源的目的就是让大家自由取用，不违法犯罪即可。（如果微调后能公开模型就更好了

**Comment by likexx** [comment]
能直接用raw text训练吗？我看别的说lora是可以用raw text直接做training data...

**Comment by HaimianYu** [comment]
请问有原始的小说数据吗

**Comment by wjord2023** [comment]
那个网盘链接好像失效了，那到哪里可以获得21.7m的那个数据集
