### ISSUE TITLE
Failed on `Loading checkpoint shards: 52%`

### ISSUE THREAD

**Issue by afif-malghani** [tloen/alpaca-lora#546]
Generate.py fails on `Loading checkpoint shards: 52%` with message `killed`.

command executed:
`$ python3 generate.py --load_8bit --base_model 'decapoda-research/llama-7b-hf' --lora_weights 'tloen/alpaca-lora-7b'`

**Comment by wangzijian121** [comment]
This problem occurred when I used the CPU for training, I increased the memory, I adjusted the 16G memory to 32G memory, and solved this problem, I hope it can help you.

![image](https://github.com/tloen/alpaca-lora/assets/40219314/024250e7-4f37-4c21-8a85-cb0014d3a664)

this
    model = LlamaForCausalLM.from_pretrained(
        base_model,
        load_in_8bit=True,
        torch_dtype=torch.float16,
        llm_int8_enable_fp32_cpu_offload=True,
        device_map={
                "transformer.word_embeddings":"cpu",
                "transformer.word_embeddings_layernorm":"cpu",
                "lm_head":"cpu",
                "transformer.h":"cpu",
                "transformer.ln_f":"cpu" ,
                "model.embed_tokens":"cpu",
                "model.layers":"cpu",
                "model.norm":"cpu"
         }

**Comment by afif-malghani** [comment]
Thank you @wangzijian121.

Yes increasing memory solved the issue, I would suggest the error message be changed for this case to reflect the cause and not just "killed" .

Closing the issue as resolved.
