### ISSUE TITLE
No output key in example 3556.

### ISSUE THREAD

**Issue by chavinlo** [tloen/alpaca-lora#55]
Hello, I have seen that you cleaned the dataset which is nice. However upon loading it into the original alpaca trainer (which is what I use) theres a line without the output key:

![image](https://user-images.githubusercontent.com/85657083/226077675-5d70506a-7ae6-4adb-95d1-3d77f5669896.png)

*I modified the trainer so that I can find it.

Just wanted to let you know.

**Comment by tloen** [comment]
Resolved. Thanks!
