### ISSUE TITLE
Question: Does training data order matter at all?

### ISSUE THREAD

**Issue by johnomeara1** [tloen/alpaca-lora#57]
I wonder if the order of the data (in https://github.com/tloen/alpaca-lora/blob/main/alpaca_data.json) matters for training.

For example, If I wanted to add my own data to the original dataset in the cleaned JSON file, would it be fine to append it to the end of the JSON? Or should I append and then shuffle the order?

Excuse my ignorance, as I am new to this technology entirely.

Regards

**Comment by collant** [comment]
I don't think the roder should matter at all, the data is shuffled before training:
![image](https://user-images.githubusercontent.com/125187079/226094361-204a1087-5c6b-4ced-89a3-e9fd079695c6.png)
From `train.py`

**Comment by johnomeara1** [comment]
Got it, Thanks!
