### ISSUE TITLE
generate.py --listen flag being ignored

### ISSUE THREAD

**Issue by ThatCoffeeGuy** [tloen/alpaca-lora#59]
Hello,

I'd like to execute generate.py the following way:

I don't want it to create a public link
I don't want it to bind to 127.0.01, instead, I want it to bind to 0.0.0.0, therefore it's accessible on the local network.

Thank you.

**Comment by dasyak** [comment]
Change the [call of launch()](https://github.com/tloen/alpaca-lora/blob/d9c19ff34eb59988ad9ed13b9148a8c3c912475d/generate.py#L136). See [gradio documentation](https://gradio.app/docs/#interface-launch-header).

**Comment by tloen** [comment]
Going to set public sharing to false by default.
