### ISSUE TITLE
Proposal: Should we create a discord or slack channel to discuss the issues?

### ISSUE THREAD

**Issue by bingjie3216** [tloen/alpaca-lora#61]
Should we create a discord or slack channel to discuss the issues?

**Comment by CDLLBOSS** [comment]
yes

**Comment by tloen** [comment]
If someone decides to create one, I'd add it to the README

**Comment by johnomeara1** [comment]
This would be awesome

**Comment by johnomeara1** [comment]
It's annoying to create issues for mundane things that generally don't have to do with the project. A discord chat would also help enhance this repo's "openness."

This is especially true for newbies like me, who have no experience with LMMs.

**Comment by felri** [comment]
@tloen https://discord.gg/prbq284xX5

**Comment by tloen** [comment]
Added!
