### ISSUE TITLE
Issues when using it with GPTQ for llama

### ISSUE THREAD

**Issue by DanielWe2** [tloen/alpaca-lora#63]
I am not sure if the issue is here in the export code or in GPTQ for LLama.

What I did:
- Used export_hf_checkpoint.py

- Executed the quantization from GPTQ for llama (https://github.com/qwopqwop200/GPTQ-for-LLaMa)

At the beginning of the quantization i got the following warning:

```
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████| 39/39 [00:11<00:00,  3.38it/s]
Some weights of the model checkpoint at ../alpaca-lora/hf_ckpt/ were not used when initializing LlamaForCausalLM: ['base_model.model.lm_head.weight']
```
Is that normal?

When I try to use the 4 bit quantized model I am only getting random output:

```
(.venv) [danielw@pc GPTQ-for-LLaMa]$ CUDA_VISIBLE_DEVICES=0 python llama_inference.py ../alpaca-lora/hf_ckpt/  --wbits 4 --load alpace-7b-4bit-non-cleaned.pt --text  "Hello"
Loading model ...
Done.
 Hello Kub Akademutionsiy?')}{\rightarrow größ office \\ größ Roberts lé?'ulseulseame collect authorizationSide色սöd São affected throwingcur let authorizationמ bug affected dw collectmineною Chairulse instant Unionistrictscherरabsरclusowclar
```

Not sure whats going on :(  It seems that the export_hf_checkpoint script exports a model that is not compatible with GPTQ for LLaMA.

**Comment by devilismyfriend** [comment]
the lora was trained on 8bit and you're applying it to a 4bit model, I assume that might be the problem

**Comment by DanielWe2** [comment]
I am using the export_hf_checkpoint.py script from this repo. From what I understand this exports the model as a 16 bit model same as the original llama hf model.

And I use then the GPTQ llama on it to make it into a 4bit model.

I tried changing `base_model.model.lm_head.weight`  to `lm_head.weight`  in the pytorch_model.bin.index.json  

This resolved the warning when loading the model. But the inference results with that model are still broken :(

**Comment by tloen** [comment]
@DanielWe2  can you try replacing
```
k.replace("base_model.model.model", "model"): v
```
with
```
k.replace("base_model.model.", ""): v
```
in `export_hf_checkpoint` and report back the results?

**Comment by DanielWe2** [comment]
@tloen 
I think that should do the same as my manual fix of the pytorch_model.bin.index.json

Which solves the warning but not the actual issue of broken output.

But I am currently trying anyway and the quantization is running. Maybe I am missing something.

**Comment by DanielWe2** [comment]
Thanks that solves the issue.
