### ISSUE TITLE
About PAD_TOKEN_ID in LLaMA

### ISSUE THREAD

**Issue by ShomyLiu** [tloen/alpaca-lora#7]
Hi,
Thanks for the finetuning code. I found that in the original LLaMa code, the pad_token_id is -1, and in your implementation, change it into 0
```
tokenizer.pad_token_id = 0
```
Would you mind explaining the reason since if the pad id is -1, we could not look up in the embedding tables.

Thanks.

**Comment by tloen** [comment]
Sure. I don't think the Facebook code has any need for pad tokens because it's just inference. But if I set the pad_toke to the eos_token, like some people have recommended, the eos_token will be ignored in training. To get both padding and an eos_toke, I just use the unk_token as the pad_token.

**Comment by ShomyLiu** [comment]
Got it. Thanks a lot.

**Comment by ChuanMeng** [comment]
Hi @tloen,
Could you please explain "the eos_token will be ignored in training"? I didn't get it.

Thank you in advance.

**Comment by apachemycat** [comment]
some actile said should set pading_token=eos ,seems correct ,if pading right
