### ISSUE TITLE
Anyone able to finetune with a different dataset?

### ISSUE THREAD

**Issue by felri** [tloen/alpaca-lora#73]
It seems that i can finetune it fine, but when I try to load the lora-alpaca folder content in my generate.py file here:

`model = PeftModel.from_pretrained(model, './lora-alpaca', torch_dtype=torch.float16)`

the script froze and nothing happens after the following generate.py function:

```python
 with torch.no_grad():
        generation_output = model.generate(
            input_ids=input_ids,
            generation_config=generation_config,
            return_dict_in_generate=True,
            output_scores=True,
            max_new_tokens=2048,
        )
```

dataset [data.zip](https://github.com/tloen/alpaca-lora/files/11011931/data.zip)

**Comment by paolorechia** [comment]
I just fine-tuned with the *same* dataset, but using the 13b model. When running the inference script, I run into the error `AttributeError: 'NoneType' object has no attribute 'device'`  and found the solution to this problem in https://github.com/huggingface/peft/issues/93.

E.g.,, in my case the code had to be changed to use the `device_map` in the `PeftModel.from_pretrained`:

```
model = LlamaForCausalLM.from_pretrained(
    model_path,
    load_in_8bit=True,
    torch_dtype=torch.float16,
    device_map="auto",
)
model = PeftModel.from_pretrained(
    model,
    alpaca_path,
    torch_dtype=torch.float16,
    device_map={"": 0}    # new line
)
```

**Comment by paolorechia** [comment]
I could give a shot trying to fine-tune with your data and see if I can reproduce your error. Did you use the original script with no modifications (except the data source, maybe)?

**Comment by HideLord** [comment]
Try to reduce the `max_new_tokens`. I had the same behavior until I reduced it to 256 or 512. I'm not sure if it's just taking a lot of time or if something breaks. It also happened only for the query: "Write the numbers from 1 to 512."
I'm also currently fine-tuning using another dataset, but it hasn't finished yet.

**Comment by paolorechia** [comment]
Since this dataset is small, I could already fine-tune a new model with your data using only one 1 epoch in just four minutes.

I can reproduce the issue, e.g., it's over 180 seconds and no answer yet. Did not try yet to reduce the `max_new_tokens` suggested by @HideLord .

While running `nvidia-smi` I see the VRAM usage going up and down, it's probably stuck trying to find an appropriate answer for some reason.

**Comment by paolorechia** [comment]
I can confirm reducing `max_new_tokens` worked here. Results are pretty garbage with just 1 epoch though :)
  
![image](https://user-images.githubusercontent.com/5386983/226200747-9c2305d0-04ee-48cd-844b-f252e2bbd42f.png)

**Comment by tloen** [comment]
Btw, I wrote some code that masks out the instruction from the loss. Have been running that overnight and hopefully will put an end to these ###instructions leaking into the outputs. If it's good enough I'll update the huggingface weights

**Comment by felri** [comment]
> just four minutes.

I think it's because of the size of the validation set, the dataset is too small so I changed it to 200, all my changes:

finetune.py
![Screenshot from 2023-03-19 16-21-22](https://user-images.githubusercontent.com/56592364/226204042-e858ab8b-d1c9-4415-92fa-8a79dd6887c6.png)

the hugging face repo change was based on a change from @tloen in generate.py

generate.py
![Screenshot from 2023-03-19 16-27-03](https://user-images.githubusercontent.com/56592364/226204144-ebcc72ce-730c-40e8-8753-a7b743fc1277.png)

after changing the max_new_tokens to 256 I do get an answer, it takes 30 seconds in my 3090 with Lora and 10 seconds without it, here are some comparisons, any ideas of why this behavior is happening? Probably related to my dataset and hyperparams but any tips are welcome.


![Screenshot from 2023-03-19 16-46-05](https://user-images.githubusercontent.com/56592364/226205061-c8bd6915-cea6-498d-b73f-ace4059cefbf.png)
![Screenshot from 2023-03-19 16-44-36](https://user-images.githubusercontent.com/56592364/226205075-aa5be3ac-6266-4a70-b6a4-736be1c04655.png)

**Comment by felri** [comment]
btw this is closed, `max_new_tokens=256` decreases the load time, thanks for the help!

**Comment by Tongcheng** [comment]
Have you found out why Lora has this behavior of repeating the outputs?

**Comment by paolorechia** [comment]
> Have you found out why Lora has this behavior of repeating the outputs?

Last LoRA I trained had a bug with the save method, I had to use to the binary from the checkpoint instead, then it worked - not sure if this is still the case. You can compare the binary sizes of the model, the correct version should have ~17mb

**Comment by Tongcheng** [comment]
Thank you! I believe I just fixed (by commenting out a few lines in finetune.py related to PEFT), it seems the repeating output still is there.
