### ISSUE TITLE
finetune 65B model on A100-80G with lora

### ISSUE THREAD

**Issue by coni-coco** [tloen/alpaca-lora#94]
It seems that we should use tensor parallel to save memory, but there is no tensor parallel in the definition of huggingface llama module. then, is it compatible with lora adapter?

**Comment by FrancescoSaverioZuppichini** [comment]
I think the bottleneck is VRAM

**Comment by Zachary-Hamel** [comment]
Do you have a guess for the amount of VRAM you'd need for 65B? I'd be curious to try it out

**Comment by coni-coco** [comment]
> Do you have a guess for the amount of VRAM you'd need for 65B? I'd be curious to try it out

at least 130G VRAM to train 65B model and 60G VRAM to train 30B model.
Use tensor parallel to partition 65B model's parameter into >= 3 A100-80G is ok. 
Is anyone know how to implement llama tensor parallel with lora adapter?

**Comment by JiexingQi** [comment]
Hi, do you know how to implement llama tensor parallel with lora adapter? @coni-coco

**Comment by JiexingQi** [comment]
Hi, do you know how to implement llama tensor parallel with lora adapter? @coni-coco
