### ISSUE TITLE
8 bit Adam

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [tloen/alpaca-lora#97]
Hi 👋 

Trying to understand how to use 8 Bit Adam from `bitsandbytes` but no luck so far.

Anyone has an idea?

Thanks 

Fra

**Comment by tloen** [comment]
You can set the optimizer to `adamw_bnb_8bit` in the training arguments. I've found that this runs slower on my machine, but YMMV.

**Comment by FrancescoSaverioZuppichini** [comment]
hi @tloen, thanks didn't know it was supported like that - it should be slower but you should save memory. I was also trying to compile / not compile the model with torch2.0 seeing not really a change. Also tried to use xformers, no luck - mmm maybe is io bound, I will try to investigate
